server/routes/computer_routes.py
from flask import Blueprint, render_template

computer_routes = Blueprint("computer", __name__)

@computer_routes.route('/computer')
def computer():
    return render_template('computer.html')

server/routes/discord_routes.py
from flask import Blueprint, render_template
import json
import threading
from discord.ext import commands
import asyncio

discord_routes = Blueprint("discord", __name__)

bot_instance = None
bot_thread = None
bot_loop = None
user_data = {}  

def start_discord_bot(token):
    global bot_instance, bot_loop

    bot_instance = commands.Bot(command_prefix="!", self_bot=True)

    @bot_instance.command()
    async def userinfo(ctx, user_id: int):
        try:
            user = await bot_instance.fetch_user(user_id)
            user_data.clear()
            user_data.update({
                "username": f"{user.name}#{user.discriminator}",
                "id": user.id,
                "created_at": user.created_at,
                "avatar": user.avatar.url
            })
        except Exception as e:
            print(f"Error fetching user {user_id}: {e}")

    bot_loop = asyncio.new_event_loop()
    asyncio.set_event_loop(bot_loop)
    bot_loop.run_until_complete(bot_instance.start(token))

@discord_routes.route('/discord')
def discord_route():
    global bot_thread

    with open("./config.json", "r") as f:
        config = json.load(f)
    discord_token = config["discord"]["token"]

    if not discord_token:
        return render_template("error.html", error_title="Required Field Missing!", error_description="You have not placed your token in the config file.", redirect="index")

    if bot_thread is None or not bot_thread.is_alive():
        bot_thread = threading.Thread(target=start_discord_bot, args=(discord_token,))
        bot_thread.start()

    return render_template('discord.html', user_data=user_data)

@discord_routes.route('/discord/stop')
def stop_discord_bot():
    global bot_instance, bot_loop, bot_thread

    if bot_instance and bot_loop and bot_thread and bot_thread.is_alive():
        asyncio.run_coroutine_threadsafe(bot_instance.close(), bot_loop)
        bot_thread.join()
        bot_instance = None
        bot_loop = None
        bot_thread = None
        return render_template('home.html')
    else:
        return render_template('discord.html', user_data=user_data)

# Display userinfo
@discord_routes.route('/discord/user_data')
def get_user_data():
    if not user_data:
        html = '''
        <div class="p-5 bg-neutral-900 border border-neutral-700 rounded"> 
            <h1 class="text-white font-semibold text-[23px]">No Users Found</h1>
            <p class="text-neutral-500 font-semibold text-[14px]">
                You have not looked up any users on Discord yet. To lookup a user, type !userinfo [user_id]
            </p>
        </div>
        <div class="p-5 bg-neutral-900 border border-neutral-700 rounded mt-3"> 
            <a href="/discord/stop" class="bg-red-600 hover:bg-red-500 text-white px-4 py-2 rounded-md font-semibold">
                Stop Discord Bot
            </a>
        </div>
        '''
    else:
        html = f'''
        <div class="p-5 bg-neutral-900 border border-neutral-700 rounded flex space-x-5 items-center"> 
            <img src="{user_data.get('avatar')}" alt="Avatar" class="w-16 h-16 rounded-full">
            <div>
                <h1 class="text-white font-semibold text-[23px]">{user_data.get('username')}</h1>
                <p class="text-neutral-500 font-semibold text-[14px]">ID: {user_data.get('id')}</p>
                <p class="text-neutral-500 font-semibold text-[14px]">Created at: {user_data.get('created_at')}</p>
            </div>
        </div>
        <div class="p-5 bg-neutral-900 border border-neutral-700 rounded mt-3"> 
            <a href="/discord/stop" class="bg-red-500 hover:bg-red-500 text-white px-4 py-2 rounded-md font-semibold">
                Stop
            </a>
        </div>
        '''
    return html

server/routes/smartlights_routes.py
from flask import Blueprint, render_template, jsonify, request
import json
import subprocess
import colorsys

smartlight_routes = Blueprint("smartlights", __name__)

class SmartLightController:
    @staticmethod
    def run(cmd, device_name="Desk LED Strip"):
        with open("./config.json", "r", encoding="utf-8") as f:
            config = json.load(f)
        
        device = config.get("smartlights", {}).get(device_name)
     
        command = [
            "kasa",
            "--host", device["ip"],
            "--username", device["username"],
            "--password", device["password"]
        ]
        
        command.extend(cmd.split())
        
        try:
            result = subprocess.run(command, capture_output=True, text=True, check=True)
            return result.stdout
        except subprocess.CalledProcessError as e:
            return f"Error running kasa command:\n{e.stderr}"

@smartlight_routes.before_request
def check_config():
    with open("./config.json", "r") as f:
        config = json.load(f)

    for device_name, device in config.get("smartlights", {}).items():
        for field, value in device.items():
            if value in ("", None):
                return render_template("error.html", error_title="Required Field Missing!", error_description=f"You're missing the required field for {field}! Please edit the config.json to resolve this error.", redirect="index")

@smartlight_routes.route('/smartlights')
def smartlights():
    with open("./config.json", "r") as f:
        config = json.load(f)
        
    smartlights = config["smartlights"]
    return render_template('smart_lights.html', smartlights=smartlights)

@smartlight_routes.route('/smartlights/on')
def smartlights_on():
    device_name = request.args.get("device")
    
    output = SmartLightController.run("on", device_name=device_name)
    
    redirection = request.args.get("redirection")
    if redirection is None:
        return render_template('smart_lights.html', smartlights=json.load(open("./config.json"))["smartlights"])
    else:
        return render_template(redirection)

@smartlight_routes.route('/smartlights/off')
def smartlights_off():
    device_name = request.args.get("device")
    
    output = SmartLightController.run("off", device_name=device_name)
    
    redirection = request.args.get("redirection")
    if redirection is None:
        return render_template('smart_lights.html', smartlights=json.load(open("./config.json"))["smartlights"])
    else:
        return render_template(redirection)

@smartlight_routes.route('/smartlights/change_color')
def change_color():
    device_name = request.args.get("device")
    hex_color = request.args.get("color")
    
    if not device_name:
        return jsonify({"error": "Device name is required"}), 400
    if not hex_color:
        return jsonify({"error": "Color parameter is required"}), 400
    
    hex_color = hex_color.lstrip('#')  
    if len(hex_color) != 6:
        return jsonify({"error": "Invalid hex color format"}), 400
    
    try:
        r = int(hex_color[0:2], 16) / 255
        g = int(hex_color[2:4], 16) / 255
        b = int(hex_color[4:6], 16) / 255
        
        h, s, v = colorsys.rgb_to_hsv(r, g, b)
        h = round(h * 360)
        s = round(s * 100)
        v = round(v * 100) 
        
        output = SmartLightController.run(f"light hsv {h} {s} {v}", device_name=device_name)
        return "", 204
    except ValueError as e:
        print(f"ValueError: {e}")
        return jsonify({"error": f"Invalid color format: {str(e)}"}), 400
    except Exception as e:
        print(f"Exception: {e}")
        return jsonify({"error": f"Failed to change color: {str(e)}"}), 500

server/routes/spotify_routes.py
from flask import Blueprint, render_template
from datetime import datetime

spotify_routes = Blueprint("spotify", __name__)

@spotify_routes.route('/spotify')
def spotify():
    return render_template('spotify.html')

server/templates/computer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PiDesk | Home</title>

    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <script src="https://unpkg.com/htmx.org@2.0.4"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../static/theme.css">
</head>
<body>
    <nav id="navigation" class="w-full p-3 bg-neutral-900 flex border-b border-b-neutral-700 justify-left gap-2">
        <a id="navigation-home-btn" href="{{ url_for('index') }}" class="px-4 py-3 rounded-md  text-white text-sm touch-manipulation select-none">
            <i class="bi bi-house-fill pointer-events-none"></i>
        </a> 
        <a id="navigation-spotify-btn" href="{{ url_for('spotify.spotify') }}" class="px-4 py-3 rounded-md  text-white text-sm touch-manipulation select-none">
            <i class="bi bi-music-note-beamed pointer-events-none"></i>
        </a>   
        <a id="navigation-computer-btn" href="{{ url_for('computer.computer') }}" class="bg-neutral-700 px-4 py-3 rounded-md border border-neutral-500 text-white text-sm touch-manipulation select-none">
            <i class="bi bi-pc-display pointer-events-none"></i>
        </a>      
        <a id="navigation-spotify-btn" href="{{ url_for('smartlights.smartlights') }}" class="px-4 py-3 rounded-md  text-white text-sm touch-manipulation select-none">
            <i class="bi bi-lightbulb-fill pointer-events-none"></i>
        </a>    
        <a id="navigation-spotify-btn" href="{{ url_for('discord.discord_route') }}" class="px-4 py-3 rounded-md  text-white text-sm touch-manipulation select-none">
            <i class="bi bi-discord pointer-events-none"></i>
        </a> 
    </nav>
</body>
</html>

server/templates/discord.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PiDesk | Home</title>

    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <script src="https://unpkg.com/htmx.org@2.0.4"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../static/theme.css">
</head>
<body>
    <nav id="navigation" class="w-full p-3 bg-neutral-900 flex border-b border-b-neutral-700 justify-left gap-2">
        <a id="navigation-home-btn" href="{{ url_for('index') }}" class="px-4 py-3 rounded-md  text-white text-sm touch-manipulation select-none">
            <i class="bi bi-house-fill pointer-events-none"></i>
        </a> 
        <a id="navigation-spotify-btn" href="{{ url_for('spotify.spotify') }}" class="px-4 py-3 rounded-md  text-white text-sm touch-manipulation select-none">
            <i class="bi bi-music-note-beamed pointer-events-none"></i>
        </a>   
        <a id="navigation-computer-btn" href="{{ url_for('computer.computer') }}" class="px-4 py-3 rounded-md  text-white text-sm touch-manipulation select-none">
            <i class="bi bi-pc-display pointer-events-none"></i>
        </a>      
        <a id="navigation-spotify-btn" href="{{ url_for('smartlights.smartlights') }}" class="px-4 py-3 rounded-md  text-white text-sm touch-manipulation select-none">
            <i class="bi bi-lightbulb-fill pointer-events-none"></i>
        </a>    
        <a id="navigation-spotify-btn" href="{{ url_for('discord.discord_route') }}" class="bg-neutral-700 px-4 py-3 rounded-md border border-neutral-500 text-white text-sm touch-manipulation select-none">
            <i class="bi bi-discord pointer-events-none"></i>
        </a> 
    </nav>
    <section class="p-5">
        <div id="user-info" hx-get="{{ url_for('discord.get_user_data') }}" hx-swap="innerHTML" hx-trigger="every 3s">
            <div class="p-5 bg-neutral-900 border border-neutral-700 rounded mb-3"> 
                <h1 class="text-white font-semibold text-[23px]">Logging in...</h1>
                <p class="text-neutral-500 font-semibold text-[14px]">
                    We are trying to log in with the token you provided.
                </p>
            </div>
        </div>
    </section>
</body>
</html>

server/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PiDesk | Home</title>

    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <script src="https://unpkg.com/htmx.org@2.0.4"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../static/theme.css">
</head>
<body>
    <nav id="navigation" class="w-full p-3 bg-neutral-900 flex border-b border-b-neutral-700 justify-left gap-2">
        <a href="{{ url_for('index') }}" class="px-4 py-3 rounded-md text-white text-sm">
            <i class="bi bi-house-fill"></i>
        </a> 
        <a href="{{ url_for('spotify.spotify') }}" class="px-4 py-3 rounded-md text-white text-sm">
            <i class="bi bi-music-note-beamed"></i>
        </a>    
        <a href="{{ url_for('computer.computer') }}" class="px-4 py-3 rounded-md text-white text-sm">
            <i class="bi bi-pc-display"></i>
        </a>  
        <a href="{{ url_for('smartlights.smartlights') }}" class="px-4 py-3 rounded-md text-white text-sm">
            <i class="bi bi-lightbulb-fill"></i>
        </a>  
    </nav>

    <section class="p-5">
        <div class="p-5 bg-neutral-900 border border-neutral-700 rounded">
            <h1 class="text-white font-semibold text-[30px]">{{ error_title }}</h1>
            <p class="text-neutral-500 font-semibold mb-3">{{ error_description }}</p>
            <a href="{{ url_for(redirect) }}" class="inline-block text-white font-semibold bg-blue-600 rounded px-4 py-2 hover:bg-blue-500 transition-colors w-full text-center">
                Go Back
            </a>       
        </div>
    </section>

    <script src="{{ url_for('static', filename='clock.js') }}"></script>      
</body>
</html>

server/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PiDesk | Home</title>

    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <script src="https://unpkg.com/htmx.org@2.0.4"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../static/theme.css">
</head>
<body>
    <nav id="navigation" class="w-full p-3 bg-neutral-900 flex border-b border-b-neutral-700 justify-left gap-2">
        <a href="{{ url_for('index') }}" class="bg-neutral-700 px-4 py-3 rounded-md border border-neutral-500 text-white text-sm">
            <i class="bi bi-house-fill"></i>
        </a> 
        <a href="{{ url_for('spotify.spotify') }}" class="px-4 py-3 rounded-md text-white text-sm">
            <i class="bi bi-music-note-beamed"></i>
        </a>    
        <a href="{{ url_for('computer.computer') }}" class="px-4 py-3 rounded-md text-white text-sm">
            <i class="bi bi-pc-display"></i>
        </a>  
        <a href="{{ url_for('smartlights.smartlights') }}" class="px-4 py-3 rounded-md text-white text-sm">
            <i class="bi bi-lightbulb-fill"></i>
        </a>  
        <a id="navigation-spotify-btn" href="{{ url_for('discord.discord_route') }}" class="px-4 py-3 rounded-md  text-white text-sm touch-manipulation select-none">
            <i class="bi bi-discord pointer-events-none"></i>
        </a> 
    </nav>

    <section class="flex-1 relative p-3 overflow-auto">
        <div class="grid grid-cols-3 grid-rows-2 gap-2">
            <!-- Clock -->
            <div class="bg-neutral-900 border border-neutral-700 rounded p-4 row-span-2">
                <p class="text-neutral-500 font-semibold text-[12px]">Clock</p>
                <h1 class="text-white font-semibold text-[29px] text-center mt-7" id="clock-time">18:02:32</h1>
                <h1 class="text-white text-[18px] mb-2 text-center" id="clock-date">Wednesday, 28 January, 2026</h1>
            </div>

            <!-- Temperature -->
            <div id="weather-temp" class="bg-neutral-900 border border-neutral-700 rounded p-4"
                hx-get="/home/update_weather_temp" hx-trigger="load, every 1800s" hx-swap="innerHTML">
                <p class="text-neutral-500 font-semibold text-[12px]">Temperature</p>
                <h1 class="text-white font-semibold text-[29px]">Loading...</h1>
            </div>

            <!-- Condition -->
            <div id="weather-cond" class="bg-neutral-900 border border-neutral-700 rounded p-4"
                hx-get="/home/update_weather_condition" hx-trigger="load, every 1800s" hx-swap="innerHTML">
                <p class="text-neutral-500 font-semibold text-[12px]">Condition</p>
                <h1 class="text-white font-semibold text-[29px]">Loading...</h1>
            </div>

            <!-- Smartlights -->
            <div class="bg-neutral-900 border border-neutral-700 rounded p-4">
                <p class="text-neutral-500 font-semibold text-[12px]">Smart Lights Desk LED Strip</p>
                <div class="flex space-x-2 mt-1">
                    <input type="color" name="color" value="#ff8800" class="w-10 h-10 rounded" hx-get="{{ url_for('smartlights.change_color', device='Desk LED Strip') }}" hx-trigger="input changed delay:300ms" hx-swap="none">
                    <a href="{{ url_for('smartlights.smartlights_on', device='Desk LED Strip', redirection='home.html') }}" class="bg-neutral-700 px-3 py-2 rounded-md border border-neutral-500 text-white text-sm touch-manipulation select-none">
                        <i class="bi bi-lightbulb-fill pointer-events-none"></i>
                    </a> 
                    <a href="{{ url_for('smartlights.smartlights_off', device='Desk LED Strip', redirection='home.html') }}" class="bg-neutral-700 px-3 py-2 rounded-md border border-neutral-500 text-white text-sm touch-manipulation select-none">
                        <i class="bi bi-lightbulb-off-fill pointer-events-none"></i>
                    </a>
                </div>
            </div>

            <!-- Location -->
            <div id="weather-loc" class="bg-neutral-900 border border-neutral-700 rounded p-4"
                hx-get="/home/update_weather_location" hx-trigger="load, every 1800s" hx-swap="innerHTML">
                <p class="text-neutral-500 font-semibold text-[12px]">Location</p>
                <h1 class="text-white font-semibold text-[29px]">Loading...</h1>
            </div>
        </div>
    </section>
    
    <script src="{{ url_for('static', filename='clock.js') }}"></script>      
</body>
</html>

server/templates/smart_lights.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PiDesk | Home</title>
    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <script src="https://unpkg.com/htmx.org@2.0.4"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../static/theme.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/> 
</head>
<body>
    <nav id="navigation" class="w-full p-3 bg-neutral-900 flex border-b border-b-neutral-700 justify-left gap-2">
        <a id="navigation-home-btn" href="{{ url_for('index') }}" class="px-4 py-3 rounded-md  text-white text-sm touch-manipulation select-none">
            <i class="bi bi-house-fill pointer-events-none"></i>
        </a> 
        <a id="navigation-spotify-btn" href="{{ url_for('spotify.spotify') }}" class="px-4 py-3 rounded-md  text-white text-sm touch-manipulation select-none">
            <i class="bi bi-music-note-beamed pointer-events-none"></i>
        </a>    
        <a id="navigation-computer-btn" href="{{ url_for('computer.computer') }}" class="px-4 py-3 rounded-md text-white text-sm touch-manipulation select-none">
            <i class="bi bi-pc-display pointer-events-none"></i>
        </a>  
        <a id="navigation-smartlights-btn" href="{{ url_for('smartlights.smartlights') }}" class="bg-neutral-700 px-4 py-3 rounded-md border border-neutral-500 text-white text-sm touch-manipulation select-none">
            <i class="bi bi-lightbulb-fill pointer-events-none"></i>
        </a> 
        <a id="navigation-spotify-btn" href="{{ url_for('discord.discord_route') }}" class="px-4 py-3 rounded-md  text-white text-sm touch-manipulation select-none">
            <i class="bi bi-discord pointer-events-none"></i>
        </a> 
    </nav>
    
    <section class="p-5">
        {% if smartlights %}
            {% for name, device in smartlights.items() %}
                <div class="mb-5 p-3 bg-neutral-900 border border-neutral-700 rounded flex items-center justify-between">
                    <div class="flex items-center space-x-3">
                        <input type="color" name="color" id="colorPicker-{{ name }}" value="#ff8800" class="w-10 h-10 rounded" hx-get="{{ url_for('smartlights.change_color', device=name) }}" hx-trigger="input changed delay:300ms" hx-swap="none">
                        <div>
                            <h1 class="text-white font-semibold">{{ name }}</h1>
                            <p class="text-neutral-500 font-semibold text-[12px]">{{ device.ip }}</p>
                        </div>
                    </div>
                    <div class="flex space-x-2">
                        <a href="{{ url_for('smartlights.smartlights_on', device=name) }}" class="bg-neutral-700 px-3 py-2 rounded-md border border-neutral-500 text-white text-sm touch-manipulation select-none">
                            <i class="bi bi-lightbulb-fill pointer-events-none"></i>
                        </a> 
                        <a href="{{ url_for('smartlights.smartlights_off', device=name) }}" class="bg-neutral-700 px-3 py-2 rounded-md border border-neutral-500 text-white text-sm touch-manipulation select-none">
                            <i class="bi bi-lightbulb-off-fill pointer-events-none"></i>
                        </a>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="mb-5 p-3 bg-neutral-900 border border-neutral-700 rounded flex items-center justify-center">
                <h1 class="text-white font-semibold">You have not added any Smartlights. To add smartlights, view the config.</h1>
            </div> 
        {% endif %}
    </section>
</body>
</html>

server/templates/spotify.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PiDesk | Spotify</title>

    <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
    <script src="https://unpkg.com/htmx.org@2.0.4"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
    <script src="https://cdn.jsdelivr.net/npm/particles.js@2.0.0/particles.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../static/theme.css">
</head>
<body>
    <nav id="navigation" class="w-full p-3 bg-neutral-900 flex border-b border-b-neutral-700 justify-left gap-2">
        <a id="navigation-home-btn" href="{{ url_for('index') }}" class="px-4 py-3 rounded-md  text-white text-sm touch-manipulation select-none">
            <i class="bi bi-house-fill pointer-events-none"></i>
        </a> 
        <a id="navigation-spotify-btn" href="{{ url_for('spotify.spotify') }}" class="bg-neutral-700 px-4 py-3 rounded-md border border-neutral-500 text-white text-sm touch-manipulation select-none">
            <i class="bi bi-music-note-beamed pointer-events-none"></i>
        </a> 
         <a id="navigation-computer-btn" href="{{ url_for('computer.computer') }}" class="px-4 py-3 rounded-md  text-white text-sm touch-manipulation select-none">
            <i class="bi bi-pc-display pointer-events-none"></i>
        </a>     
        <a id="navigation-spotify-btn" href="{{ url_for('smartlights.smartlights') }}" class="px-4 py-3 rounded-md  text-white text-sm touch-manipulation select-none">
            <i class="bi bi-lightbulb-fill pointer-events-none"></i>
        </a> 
        <a id="navigation-spotify-btn" href="{{ url_for('discord.discord_route') }}" class="px-4 py-3 rounded-md  text-white text-sm touch-manipulation select-none">
            <i class="bi bi-discord pointer-events-none"></i>
        </a> 
    </nav>
</body>
</html>